version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./dist s3://dev-buyers.kuuzza.store
      - aws cloudfront create-invalidation --distribution-id E3OF19T713LFQR --paths "/*";